### ISSUE TITLE
Milestones?

### ISSUE THREAD

**Issue by hklarner** [hklarner/PyBoolNet#53]
I am wondering if we should collect Ideas about changes in PyBoolNet that we would like to see that are version breaking.

For example, I noticed that, years ago when I wrote PyBoolNet I decided for whatever reason to capitalize argument names :roll_eyes: Changing this to lower case would be a breaking change for anyone using PyBoolNet with function calls that use named arguments which is why haven't made the change yet.

Would you like to see such a change?

Do you have other suggestions / ideas?

**Comment by hklarner** [comment]
I'll keep a full list of what could be interesting here:

- [ ] lower case for module names and parameter names (`PyBoolNet` -> `pyboolnet`, `create_igraph(Primes)` -> `create_igraph(primes)`)
- [ ] drop support for Python 2.x
- [ ] use doctests
- [ ] replace verbosity arguments with proper logging (`silent: bool` -> `log.debug(..)`)
- [ ] replace JSON structure with Python's dataclasses
